"""
vLLM Factory CLI — The LEGO Builder.

Scaffold new plugins from composable building blocks:
    forge init my-model --base modernbert --pooler colbert
    forge list models
    forge list poolers
    forge list kernels
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .registry import list_components

# ── Plugin templates ─────────────────────────────────────────────

INIT_TEMPLATE = '''\
"""
{plugin_title} Plugin for vLLM

Auto-generated by vLLM Factory. Customize to fit your model.
"""

from .model import {model_class}
from .config import {config_class}

from forge.registration import register_with_vllm, register_config


def register():
    """Register this plugin with vLLM. Called via entry point."""
    register_with_vllm("{architecture_name}", {model_class})
    register_config("{model_type}", {config_class})


# Auto-register on import
register()

__all__ = ["{model_class}", "{config_class}", "register"]
'''

CONFIG_TEMPLATE = '''\
"""
Configuration for {plugin_title}.

Extends the base model's config with task-specific parameters.
"""

from transformers import PretrainedConfig


class {config_class}(PretrainedConfig):
    """Configuration for {plugin_title}."""

    model_type = "{model_type}"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        # TODO: Add your model-specific config parameters here
        # Example:
        # self.output_dim = kwargs.get("output_dim", 128)
'''

MODEL_TEMPLATE = '''\
"""
{plugin_title} model for vLLM.

Composes a base encoder with a custom pooler head.
Auto-generated by vLLM Factory — customize as needed.
"""

from typing import Iterable, Optional, Tuple

import torch
import torch.nn as nn

from vllm.config import VllmConfig
from vllm.sequence import IntermediateTensors
from vllm.model_executor.models.interfaces_base import attn_type, default_pooling_type

from .config import {config_class}


@attn_type("encoder_only")
@default_pooling_type(tok_pooling_type="ALL")
class {model_class}(nn.Module):
    """{plugin_title} — encoder + pooler for vLLM.

    TODO: Import your base model and pooler, wire them together.
    """

    is_pooling_model = True

    def __init__(self, *, vllm_config: VllmConfig, prefix: str = ""):
        super().__init__()
        config = vllm_config.model_config.hf_config
        self.config = config

        # TODO: Initialize your encoder (custom or vLLM built-in)
        # from vllm.model_executor.models.modernbert import ModernBertModel
        # self.model = ModernBertModel(vllm_config=vllm_config, prefix=f"{{prefix}}.model")

        # TODO: Initialize your pooler head
        # from poolers.colbert_pooler import ColBERTPooler
        # self.pooler = ColBERTPooler(hidden_size=config.hidden_size)

    def forward(
        self,
        input_ids: torch.Tensor,
        positions: torch.Tensor,
        intermediate_tensors: Optional[IntermediateTensors] = None,
        inputs_embeds: Optional[torch.Tensor] = None,
        **kwargs,
    ) -> torch.Tensor:
        """Forward pass: encoder → projection → output."""
        # TODO: Run your encoder
        # hidden_states = self.model(input_ids, positions, ...)
        # return self.pooler(hidden_states)
        raise NotImplementedError("Implement forward() with your encoder + pooler")

    def load_weights(self, weights: Iterable[Tuple[str, torch.Tensor]]) -> set[str]:
        """Load weights from checkpoint."""
        # TODO: Map checkpoint keys to your model's parameters
        # Use forge.weight_utils.load_weights_from_mapping() for common patterns
        raise NotImplementedError("Implement load_weights() for your checkpoint format")
'''

SETUP_TEMPLATE = '''\
"""
{plugin_title} vLLM Plugin

Install with: pip install -e .
"""

from setuptools import setup, find_packages

setup(
    name="vllm-{plugin_name}-plugin",
    version="0.1.0",
    description="{plugin_title} plugin for vLLM",
    author="Your Name",
    packages=find_packages(),
    python_requires=">=3.11",
    install_requires=[
        "torch>=2.0",
        "transformers>=4.40",
    ],
    entry_points={{
        "vllm.general_plugins": [
            "{plugin_name} = {package_name}:register",
        ],
    }},
)
'''

README_TEMPLATE = """\
# {plugin_title}

> Auto-generated by [vLLM Factory](https://github.com/ddickmann/vllm-factory)

## Components

| Component | Source |
|-----------|--------|
| Base Model | `{base_model}` |
| Pooler | `{pooler}` |
| Kernels | {kernels} |

## Installation

```bash
pip install -e .
```

## Usage

```python
from vllm import LLM

# Plugin auto-registers via entry point
llm = LLM(
    model="your-model-id",
    task="embed",  # or "classify" for token classification
    trust_remote_code=True,
)
```

## Development

```bash
# Run tests
pytest tests/ -v

# Check parity with reference model
python -m forge.testing.harness --plugin {plugin_name}
```
"""


def cmd_init(args: argparse.Namespace) -> None:
    """Scaffold a new plugin from building blocks."""
    name = args.name
    base = args.base or "vllm:ModernBertModel"
    pooler = args.pooler or "none"
    kernels = args.kernels or []

    # Derive names
    plugin_name = name.replace("-", "_").replace(" ", "_").lower()
    class_base = "".join(w.capitalize() for w in name.replace("-", " ").replace("_", " ").split())
    model_class = f"{class_base}Model"
    config_class = f"{class_base}Config"
    architecture_name = model_class
    model_type = plugin_name
    plugin_title = name.replace("-", " ").replace("_", " ").title()
    package_name = plugin_name

    # Create directory
    target_dir = Path(args.output or f"plugins/{plugin_name}")
    target_dir.mkdir(parents=True, exist_ok=True)

    # Generate files
    fmt_kwargs = dict(
        plugin_name=plugin_name,
        plugin_title=plugin_title,
        model_class=model_class,
        config_class=config_class,
        architecture_name=architecture_name,
        model_type=model_type,
        package_name=package_name,
        base_model=base,
        pooler=pooler,
        kernels=", ".join(kernels) if kernels else "None",
    )

    files = {
        "__init__.py": INIT_TEMPLATE.format(**fmt_kwargs),
        "config.py": CONFIG_TEMPLATE.format(**fmt_kwargs),
        "model.py": MODEL_TEMPLATE.format(**fmt_kwargs),
        "setup.py": SETUP_TEMPLATE.format(**fmt_kwargs),
        "README.md": README_TEMPLATE.format(**fmt_kwargs),
    }

    for filename, content in files.items():
        filepath = target_dir / filename
        if filepath.exists() and not args.force:
            print(f"  ⏭  {filepath} (exists, use --force to overwrite)")
            continue
        filepath.write_text(content)
        print(f"  ✓  {filepath}")

    print(f"\n🔨 Plugin scaffolded at {target_dir}/")
    print("   Next: edit model.py to wire up your encoder + pooler")
    print(f"   Then: pip install -e {target_dir}")


def cmd_list(args: argparse.Namespace) -> None:
    """List available building blocks."""
    category = args.category

    if category not in ("models", "poolers", "kernels", "processors", "all"):
        print(f"Unknown category: {category}")
        print("Available: models, poolers, kernels, processors, all")
        sys.exit(1)

    # Map CLI plural to registry singular
    cat_map = {
        "models": "model",
        "poolers": "pooler",
        "kernels": "kernel",
        "processors": "processor",
    }

    if category == "all":
        categories = ["model", "pooler", "kernel", "processor"]
    else:
        categories = [cat_map[category]]

    for cat in categories:
        components = list_components(cat)
        if not components:
            continue
        print(f"\n{'─' * 60}")
        print(f"  {cat.upper()}S")
        print(f"{'─' * 60}")
        for comp in components:
            tags = " ".join(f"[{t}]" for t in comp.tags) if comp.tags else ""
            print(f"  {comp.name:<30} {comp.description}")
            if tags:
                print(f"  {'':30} {tags}")
        print()


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="forge",
        description="vLLM Factory — Build custom vLLM model plugins from LEGO blocks",
    )
    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # forge init
    init_parser = subparsers.add_parser("init", help="Scaffold a new plugin")
    init_parser.add_argument("name", help="Plugin name (e.g., my-colbert-model)")
    init_parser.add_argument(
        "--base", help="Base model component (e.g., modernbert, vllm:ModernBertModel)"
    )
    init_parser.add_argument("--pooler", help="Pooler component (e.g., colbert, gliner_span)")
    init_parser.add_argument(
        "--kernels", nargs="*", help="Kernel components (e.g., fused_glu fused_layernorm)"
    )
    init_parser.add_argument("--output", "-o", help="Output directory (default: plugins/<name>/)")
    init_parser.add_argument("--force", "-f", action="store_true", help="Overwrite existing files")

    # forge list
    list_parser = subparsers.add_parser("list", help="List available building blocks")
    list_parser.add_argument(
        "category",
        nargs="?",
        default="all",
        help="Category: models, poolers, kernels, processors, all",
    )

    args = parser.parse_args()

    if args.command == "init":
        cmd_init(args)
    elif args.command == "list":
        cmd_list(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
